import type {
  Category,
  Theme,
  Tag,
  Store,
  Product,
  MarketplaceStats,
  DummyDataBundle,
} from './types';

export const categories: Category[] = [
  {
    id: 'cat-saas',
    name: 'SaaS Templates',
    slug: 'saas-templates',
    icon: 'server',
    description: 'Launch high-converting SaaS marketing sites with modular sections.',
  },
  {
    id: 'cat-ecommerce',
    name: 'E-commerce',
    slug: 'ecommerce',
    icon: 'shopping-bag',
    description: 'Complete storefronts with carts, payments, and analytics dashboards.',
  },
  {
    id: 'cat-portfolio',
    name: 'Portfolio',
    slug: 'portfolio',
    icon: 'briefcase',
    description: 'Airtight personal portfolios for designers and developers.',
  },
  {
    id: 'cat-landing',
    name: 'Landing Pages',
    slug: 'landing-pages',
    icon: 'rocket',
    description: 'Launch-ready hero, pricing, and testimonial pages built to convert.',
  },
  {
    id: 'cat-dashboard',
    name: 'Dashboards',
    slug: 'dashboards',
    icon: 'layout-dashboard',
    description: 'Full-stack admin dashboards wired with data visualizations.',
  },
  {
    id: 'cat-education',
    name: 'Education',
    slug: 'education',
    icon: 'graduation-cap',
    description: 'Learning platforms, cohort classrooms, and LMS kits.',
  },
];

export const themes: Theme[] = [
  {
    id: 'theme-neo',
    name: 'Neo Tech',
    slug: 'neo-tech',
    palette: 'from-blue-500 via-sky-500 to-cyan-400',
    tagline: 'Futuristic gradients with glassmorphism highlights.',
  },
  {
    id: 'theme-serene',
    name: 'Serene Studio',
    slug: 'serene-studio',
    palette: 'from-indigo-400 via-purple-400 to-pink-400',
    tagline: 'Soft visuals with airy spacing for creative portfolios.',
  },
  {
    id: 'theme-summit',
    name: 'Summit Finance',
    slug: 'summit-finance',
    palette: 'from-slate-900 via-slate-800 to-blue-600',
    tagline: 'Trust-driven aesthetics tailor-made for fintech.',
  },
  {
    id: 'theme-vital',
    name: 'Vital Health',
    slug: 'vital-health',
    palette: 'from-emerald-400 via-teal-400 to-cyan-300',
    tagline: 'Clean wellness UI with calm gradients and legible typography.',
  },
  {
    id: 'theme-learn',
    name: 'Learn Loop',
    slug: 'learn-loop',
    palette: 'from-orange-400 via-amber-400 to-yellow-300',
    tagline: 'Playful yet clear visuals for learning experiences.',
  },
  {
    id: 'theme-agency',
    name: 'Agency Pulse',
    slug: 'agency-pulse',
    palette: 'from-blue-600 via-blue-500 to-indigo-500',
    tagline: 'Bold, confident layouts for boutique agencies.',
  },
];

export const tags: Tag[] = [
  { id: 'tag-nextjs', name: 'Next.js', slug: 'nextjs' },
  { id: 'tag-react', name: 'React', slug: 'react' },
  { id: 'tag-tailwind', name: 'Tailwind CSS', slug: 'tailwind-css' },
  { id: 'tag-laravel', name: 'Laravel', slug: 'laravel' },
  { id: 'tag-stripe', name: 'Stripe', slug: 'stripe' },
  { id: 'tag-supabase', name: 'Supabase', slug: 'supabase' },
  { id: 'tag-ai', name: 'AI', slug: 'ai' },
  { id: 'tag-ecommerce', name: 'Commerce', slug: 'commerce' },
  { id: 'tag-landing', name: 'Landing', slug: 'landing' },
  { id: 'tag-dashboard', name: 'Dashboard', slug: 'dashboard' },
  { id: 'tag-automation', name: 'Automation', slug: 'automation' },
  { id: 'tag-analytics', name: 'Analytics', slug: 'analytics' },
];

export const stores: Store[] = [
  {
    id: 'store-stellarforge',
    slug: 'stellarforge',
    name: 'Stellar Forge',
    tagline: 'Premium SaaS starter kits crafted for speed.',
    bio: 'We build production-grade SaaS kits with clean code, beautiful UI, and ready-to-ship integrations so you can launch in days, not months.',
    avatarUrl: 'https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=200&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1527443224154-d2af8728ef03?auto=format&fit=crop&w=1200&q=80',
    rating: 4.9,
    reviewCount: 428,
    totalSales: 8920,
    responseTime: '1h avg',
    badges: ['Top Rated', 'Lightning Support'],
    socials: [
      { platform: 'twitter', url: 'https://twitter.com/stellarforge' },
      { platform: 'github', url: 'https://github.com/stellarforge' },
      { platform: 'website', url: 'https://stellarforge.dev' },
    ],
  },
  {
    id: 'store-hypercraft',
    slug: 'hypercraft',
    name: 'Hypercraft Studio',
    tagline: 'Design-led templates for modern agencies.',
    bio: 'A team of designers and front-end engineers delivering expressive templates that stay performant and accessible.',
    avatarUrl: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?auto=format&fit=crop&w=200&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=1200&q=80',
    rating: 4.8,
    reviewCount: 286,
    totalSales: 5431,
    responseTime: '2h avg',
    badges: ['Design System'],
    socials: [
      { platform: 'dribbble', url: 'https://dribbble.com/hypercraft' },
      { platform: 'linkedin', url: 'https://linkedin.com/company/hypercraft' },
    ],
  },
  {
    id: 'store-orbitlabs',
    slug: 'orbit-labs',
    name: 'Orbit Labs',
    tagline: 'Engineering automation for the no-code world.',
    bio: 'We combine AI tooling with pragmatic engineering to deliver workflows, dashboards, and API-first templates.',
    avatarUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=200&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1200&q=80',
    rating: 4.7,
    reviewCount: 192,
    totalSales: 3120,
    responseTime: '45m avg',
    badges: ['Automation', 'AI Verified'],
    socials: [
      { platform: 'twitter', url: 'https://twitter.com/orbitlabs' },
      { platform: 'github', url: 'https://github.com/orbitlabs' },
      { platform: 'website', url: 'https://orbitlabs.ai' },
    ],
  },
];

const makeDate = (offset: number) => new Date(Date.UTC(2024, 7, 1 + offset)).toISOString();

export const products: Product[] = [
  {
    id: 'prod-saas-nova',
    slug: 'nova-saas-starter',
    storeId: 'store-stellarforge',
    title: 'Nova SaaS Starter',
    description:
      'Full-stack SaaS boilerplate with onboarding flows, billing, analytics, and role-based access control.',
    priceCents: 24900,
    currency: 'USD',
    rating: 4.9,
    reviewCount: 182,
    totalSales: 2410,
    featured: true,
    stack: ['Next.js', 'Supabase', 'Stripe', 'Tailwind CSS'],
    categoryIds: ['cat-saas', 'cat-dashboard'],
    themeIds: ['theme-neo'],
    tagIds: ['tag-nextjs', 'tag-stripe', 'tag-supabase', 'tag-dashboard'],
    demoUrl: 'https://demo.marketplace-web.dev/nova',
    thumbnailUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=900&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1506765515384-028b60a970df?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?auto=format&fit=crop&w=1400&q=80',
    ],
    highlights: [
      'Subscription billing with Stripe Invoices',
      'AI-powered onboarding concierge',
      'Tenant-aware analytics dashboard',
    ],
    status: 'published',
    createdAt: makeDate(1),
    updatedAt: makeDate(12),
  },
  {
    id: 'prod-saas-orion',
    slug: 'orion-support-suite',
    storeId: 'store-stellarforge',
    title: 'Orion Support Suite',
    description:
      'Customer success dashboard with ticketing, knowledge base, and sentiment analytics ready to deploy.',
    priceCents: 18900,
    currency: 'USD',
    rating: 4.8,
    reviewCount: 136,
    totalSales: 1580,
    featured: false,
    stack: ['Next.js', 'Postgres', 'Tailwind CSS', 'OpenAI'],
    categoryIds: ['cat-dashboard', 'cat-saas'],
    themeIds: ['theme-summit'],
    tagIds: ['tag-nextjs', 'tag-dashboard', 'tag-analytics', 'tag-ai'],
    demoUrl: 'https://demo.marketplace-web.dev/orion',
    thumbnailUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=900&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1518744387222-1475405965d4?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?auto=format&fit=crop&w=1400&q=80',
    ],
    highlights: [
      'Omnichannel inbox with AI triage',
      'Team performance analytics',
      'Knowledge base with search embeddings',
    ],
    status: 'published',
    createdAt: makeDate(4),
    updatedAt: makeDate(10),
  },
  {
    id: 'prod-landing-clarity',
    slug: 'clarity-landing-collection',
    storeId: 'store-hypercraft',
    title: 'Clarity Landing Collection',
    description:
      'Bundle of 8 high-impact landing pages with modular hero, pricing, FAQ, and testimonial sections.',
    priceCents: 12900,
    currency: 'USD',
    rating: 4.7,
    reviewCount: 98,
    totalSales: 1320,
    featured: true,
    stack: ['Next.js', 'React', 'Tailwind CSS'],
    categoryIds: ['cat-landing'],
    themeIds: ['theme-serene'],
    tagIds: ['tag-nextjs', 'tag-landing', 'tag-tailwind'],
    demoUrl: 'https://demo.marketplace-web.dev/clarity',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551292831-023188e78222?auto=format&fit=crop&w=900&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1523475472560-d2df97ec485c?auto=format&fit=crop&w=1400&q=80',
    ],
    highlights: [
      'Sections built with shadcn/ui primitives',
      'Accessibility-first components',
      'Responsive typography scale',
    ],
    status: 'published',
    createdAt: makeDate(7),
    updatedAt: makeDate(14),
  },
  {
    id: 'prod-ecommerce-pulse',
    slug: 'pulse-commerce-kit',
    storeId: 'store-orbitlabs',
    title: 'Pulse Commerce Kit',
    description:
      'Headless commerce starter with product discovery, cart, checkout, and customer portal powered by Stripe.',
    priceCents: 27900,
    currency: 'USD',
    rating: 4.9,
    reviewCount: 154,
    totalSales: 1890,
    featured: true,
    stack: ['Next.js', 'Stripe', 'Supabase', 'Tailwind CSS'],
    categoryIds: ['cat-ecommerce', 'cat-dashboard'],
    themeIds: ['theme-neo'],
    tagIds: ['tag-nextjs', 'tag-stripe', 'tag-ecommerce', 'tag-dashboard'],
    demoUrl: 'https://demo.marketplace-web.dev/pulse',
    thumbnailUrl: 'https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=900&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1400&q=80',
    ],
    highlights: [
      'Optimistic UI cart interactions',
      'Real-time inventory sync via Supabase',
      'Embedded customer analytics dashboard',
    ],
    status: 'published',
    createdAt: makeDate(9),
    updatedAt: makeDate(15),
  },
  {
    id: 'prod-portfolio-lumen',
    slug: 'lumen-portfolio-stack',
    storeId: 'store-hypercraft',
    title: 'Lumen Portfolio Stack',
    description:
      'Portfolio system with case study builder, global theming, and motion-ready hero sections.',
    priceCents: 9900,
    currency: 'USD',
    rating: 4.6,
    reviewCount: 64,
    totalSales: 880,
    featured: false,
    stack: ['Next.js', 'Framer Motion', 'Tailwind CSS'],
    categoryIds: ['cat-portfolio'],
    themeIds: ['theme-serene'],
    tagIds: ['tag-nextjs', 'tag-tailwind', 'tag-react'],
    demoUrl: 'https://demo.marketplace-web.dev/lumen',
    thumbnailUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=900&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1400&q=80',
    ],
    highlights: [
      'Case study markdown renderer',
      'Dark/light theme toggle baked in',
      'Smooth reveal animations by default',
    ],
    status: 'published',
    createdAt: makeDate(11),
    updatedAt: makeDate(16),
  },
  {
    id: 'prod-edu-catalyst',
    slug: 'catalyst-cohort-platform',
    storeId: 'store-orbitlabs',
    title: 'Catalyst Cohort Platform',
    description:
      'Learning management system with cohort scheduling, live sessions, and progress analytics.',
    priceCents: 21900,
    currency: 'USD',
    rating: 4.8,
    reviewCount: 112,
    totalSales: 1280,
    featured: false,
    stack: ['Next.js', 'Supabase', 'OpenAI', 'Tailwind CSS'],
    categoryIds: ['cat-education', 'cat-dashboard'],
    themeIds: ['theme-learn'],
    tagIds: ['tag-nextjs', 'tag-supabase', 'tag-ai', 'tag-automation'],
    demoUrl: 'https://demo.marketplace-web.dev/catalyst',
    thumbnailUrl: 'https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?auto=format&fit=crop&w=900&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1400&q=80',
    ],
    highlights: [
      'Session recording & playback hub',
      'AI feedback loops for assignments',
      'Cohort calendar with ICS sync',
    ],
    status: 'published',
    createdAt: makeDate(13),
    updatedAt: makeDate(17),
  },
  {
    id: 'prod-dashboard-falcon',
    slug: 'falcon-analytics-suite',
    storeId: 'store-stellarforge',
    title: 'Falcon Analytics Suite',
    description:
      'Modular analytics dashboard with streaming metrics, anomaly detection, and KPI storytelling.',
    priceCents: 25900,
    currency: 'USD',
    rating: 5,
    reviewCount: 92,
    totalSales: 1020,
    featured: false,
    stack: ['Next.js', 'ClickHouse', 'Tailwind CSS'],
    categoryIds: ['cat-dashboard'],
    themeIds: ['theme-summit'],
    tagIds: ['tag-nextjs', 'tag-analytics', 'tag-dashboard'],
    demoUrl: 'https://demo.marketplace-web.dev/falcon',
    thumbnailUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=900&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1525182008055-f88b95ff7980?auto=format&fit=crop&w=1400&q=80',
    ],
    highlights: [
      'Timeseries visualizations with streaming sockets',
      'Alerting rules with Slack webhooks',
      'Story mode for stakeholder reporting',
    ],
    status: 'published',
    createdAt: makeDate(14),
    updatedAt: makeDate(18),
  },
  {
    id: 'prod-ecommerce-voyage',
    slug: 'voyage-marketplace-template',
    storeId: 'store-orbitlabs',
    title: 'Voyage Marketplace Template',
    description:
      'Multi-vendor marketplace with onboarding workflows, payout reporting, and review moderation.',
    priceCents: 29900,
    currency: 'USD',
    rating: 4.7,
    reviewCount: 78,
    totalSales: 910,
    featured: false,
    stack: ['Next.js', 'Stripe Connect', 'Supabase'],
    categoryIds: ['cat-ecommerce', 'cat-saas'],
    themeIds: ['theme-neo'],
    tagIds: ['tag-nextjs', 'tag-stripe', 'tag-ecommerce', 'tag-automation'],
    demoUrl: 'https://demo.marketplace-web.dev/voyage',
    thumbnailUrl: 'https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=900&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1523475472560-d2df97ec485c?auto=format&fit=crop&w=1400&q=80',
    ],
    highlights: [
      'Vendor onboarding with KYC steps',
      'Stripe Connect payouts and reporting',
      'Rating and dispute workflow modules',
    ],
    status: 'published',
    createdAt: makeDate(15),
    updatedAt: makeDate(20),
  },
  {
    id: 'prod-landing-aurora',
    slug: 'aurora-launch-kit',
    storeId: 'store-hypercraft',
    title: 'Aurora Launch Kit',
    description:
      'Glassy hero layouts with staggered motion, ideal for product launches and waitlist campaigns.',
    priceCents: 8900,
    currency: 'USD',
    rating: 4.5,
    reviewCount: 52,
    totalSales: 740,
    featured: false,
    stack: ['Next.js', 'Framer Motion', 'Tailwind CSS'],
    categoryIds: ['cat-landing'],
    themeIds: ['theme-agency'],
    tagIds: ['tag-nextjs', 'tag-tailwind', 'tag-landing'],
    demoUrl: 'https://demo.marketplace-web.dev/aurora',
    thumbnailUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1579403124614-197f69d8187b?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1400&q=80',
    ],
    highlights: [
      'Waitlist form with analytics events',
      'Hero wave animation powered by CSS variables',
      'SEO-ready metadata builder',
    ],
    status: 'published',
    createdAt: makeDate(16),
    updatedAt: makeDate(21),
  },
  {
    id: 'prod-portfolio-halo',
    slug: 'halo-freelancer-pack',
    storeId: 'store-hypercraft',
    title: 'Halo Freelancer Pack',
    description:
      'Bundle of freelancer portfolio templates with booking calendar and proposal builder.',
    priceCents: 7900,
    currency: 'USD',
    rating: 4.6,
    reviewCount: 61,
    totalSales: 670,
    featured: false,
    stack: ['Next.js', 'Calendly API', 'Tailwind CSS'],
    categoryIds: ['cat-portfolio'],
    themeIds: ['theme-serene'],
    tagIds: ['tag-nextjs', 'tag-tailwind', 'tag-automation'],
    demoUrl: 'https://demo.marketplace-web.dev/halo',
    thumbnailUrl: 'https://images.unsplash.com/photo-1523263666618-1b7d63d0316f?auto=format&fit=crop&w=900&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1486652980104-54f4d2820f5b?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1492724441997-5dc865305da7?auto=format&fit=crop&w=1400&q=80',
    ],
    highlights: [
      'Proposal system with e-sign placeholders',
      'Booking calendar integration',
      'Template pack with light and dark variants',
    ],
    status: 'published',
    createdAt: makeDate(17),
    updatedAt: makeDate(22),
  },
  {
    id: 'prod-health-pulse',
    slug: 'vitality-health-dashboard',
    storeId: 'store-orbitlabs',
    title: 'Vitality Health Dashboard',
    description:
      'HIPAA-ready patient engagement dashboard with telehealth scheduling and wellbeing analytics.',
    priceCents: 26900,
    currency: 'USD',
    rating: 4.8,
    reviewCount: 74,
    totalSales: 580,
    featured: false,
    stack: ['Next.js', 'Supabase', 'Tailwind CSS', 'Recharts'],
    categoryIds: ['cat-dashboard', 'cat-education'],
    themeIds: ['theme-vital'],
    tagIds: ['tag-nextjs', 'tag-supabase', 'tag-dashboard', 'tag-analytics'],
    demoUrl: 'https://demo.marketplace-web.dev/vitality',
    thumbnailUrl: 'https://images.unsplash.com/photo-1583912268184-8385d3f5dd4a?auto=format&fit=crop&w=900&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1518733057094-95b53147fdd9?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?auto=format&fit=crop&w=1400&q=80',
    ],
    highlights: [
      'Patient messaging with moderation hooks',
      'Telehealth scheduling & reminders',
      'Insights powered by wellbeing score models',
    ],
    status: 'published',
    createdAt: makeDate(18),
    updatedAt: makeDate(23),
  },
];

export const marketplaceStats: MarketplaceStats = {
  totalProducts: products.length,
  totalSellers: stores.length,
  totalDownloads: products.reduce((acc, product) => acc + product.totalSales, 0),
  satisfactionRate: 96,
};

export const dummyData: DummyDataBundle = {
  categories,
  themes,
  tags,
  stores,
  products,
  marketplaceStats,
};

